repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.2
  hooks:
    - id: ruff
    - id: ruff-format
      args: [--config, ./pyproject.toml]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.0
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
    - id: black
      args:
        - --safe
        - --quiet
      files: ^((xbox|tests)/.+)?[^/]+\.py$
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
    - id: bandit
      args:
        - --configfile=pyproject.toml
        - --quiet
        - --format=custom
      files: ^(xbox|tests)/.+\.py$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-executables-have-shebangs
      stages: [manual]
    - id: check-json